# Example configuration for Hyperliquid data source
data_source:
  source_type: hyperliquid
  network: mainnet  # mainnet or testnet
  tickers:
    - BTC
    - ETH
    - SOL
  interval: 1m  # 1 minute candles
  api_config:
    api_key: YOUR_API_KEY_HERE
    secret: YOUR_SECRET_HERE

server:
  host: 0.0.0.0
  port: 8000
  ping_interval: 20
  ping_timeout: 20

initial_cash: 100000.0